import 'constants_methods.dart';

class ImageStrings {
  ImageStrings._();

  //Gif image
  static const String loader = "${assetImagePathIcons}loader.gif";

  //PNG images
  static const String closeIcon = "${assetImagePathIcons}close_icon.png";
  static const String dashboard = "${assetImagePathIcons}dashboard.png";
  static const String performanceDashboard = "${assetImagePathIcons}performance_dashboard.png";
  static const String eidBackDemo = "${assetImagePathIcons}eid_back_demo.png";
  static const String eidFrontDemo = "${assetImagePathIcons}eid_front_demo.png";
  static const String greenLogo = "${assetImagePathIcons}green_logo.png";
  static const String learnAndDevCard = "${assetImagePathIcons}learn_and_dev_card.png";
  static const String mandatoryAssignment = "${assetImagePathIcons}mandatory_assignment.png";
  static const String shadowBottom = "${assetImagePathIcons}shadow_bottom.png";
  static const String shadowTop = "${assetImagePathIcons}shadow_top.png";
  static const String splashIcon = "${assetImagePathIcons}splash_icon.png";
  static const String storyView1 = "${assetImagePathIcons}story_view1.png";
  static const String storyView2 = "${assetImagePathIcons}story_view2.png";
  static const String storyView3 = "${assetImagePathIcons}story_view3.png";
  static const String uaeFlag = "${assetImagePathIcons}uae_flag.png";
  static const String newArrivalTag = "${assetImagePathIcons}new_arrival_tag.png";
  static const String crossButton = "${assetImagePathIcons}cross_button.png";
  static const String profilePlaceholderIcon = "${assetImagePathIcons}profile_placeholder_image.png";
  static const String placeHolderImage = "${assetImagePathIcons}placeholder.png";
  static const String placeholder = "${assetImagePathIcons}placeholder.png";
  static const String searchMagnifyingGlass = "${assetImagePathIcons}magnifying_glass.png";
  static const String jeweleryShoppingCart = "jewelery_shopping_cart.svg";
  static const String jeweleryBell = "jewelery_bell.svg";
  static const String searchCrossIcon = "${assetImagePathIcons}close.png";
  static const String searchIconPng = "${assetImagePathIcons}MagnifyingGlass2.png";
  static const String emptyCartPng = "empty_cart.png";


  // //SVG images
  // static const String accountMail = "account_mail.svg";
  // static const String address1Icon = "address1icon.svg";
  // static const String bankIcon = "bank_icon.svg";
  // static const String bankNameIcon = "bank_name_icon.svg";
  // static const String appIcon = "app_icon.svg";
  // static const String barChartIcon = "bar_chart_icon.svg";
  // static const String bell = "bell.svg";
  // static const String bellIcon = "bell_icon.svg";
  // static const String bookIcon = "bookicon.svg";
  // static const String button = "button.svg";
  // static const String calenderIcon = "calendar_icon.svg";
  // static const String capIcon = "capicon.svg";
  // static const String chartPieSelected = "chart_pie_selected.svg";
  // static const String chartPieUnSelected = "chart_pie_unselected.svg";
  // static const String checkUnderScoreCircle = "check_circle.svg";
  // static const String checkDashCircle = "check-circle.svg";
  // static const String checkCircleClosed = "check-circle-closed.svg";
  // static const String checkCross = "check_cross.svg";
  // static const String circularArrow = "circular_arrow.svg";
  // static const String city = "city.svg";
  // static const String closeIcons = "close_icon.svg";
  // static const String cross = "cross.svg";
  // static const String disabledCheck = "disabled_check.svg";
  // static const String downArrow = "down_arrow.svg";
  // static const String dropDownIcon = "dropdownicon.svg";
  // static const String email = "email.svg";
  // static const String emailOtpIcon = "email_otp_icon.svg";
  // static const String envelope = "envelope.svg";
  // static const String face = "face.svg";
  // static const String faceViewFinder = "face-viewfinder.svg";
  // static const String faceIdIcon = "face_id_icon.svg";
  // static const String failureIcon = "failure_icon.svg";
  // static const String fingerPrint = "finger_print.svg";
  // static const String globeIcon = "globeicon.svg";
  // static const String greenCheck = "green_check.svg";
  // static const String headsetIcon = "headset_icon.svg";
  // static const String heartSelected = "heart_selected.svg";
  // static const String heartUnSelected = "heart_unselected.svg";
  // static const String helpIcon = "help_icon.svg";
  // static const String homeSelected = "home_selected.svg";
  // static const String homeUnSelected = "home_unselected.svg";
  // static const String infoCircle = "info-circle.svg";
  // static const String infoHelpIcon = "info_help_icon.svg";
  // static const String infoImage = "info_image.svg";
  // static const String languageScreenShadowBottom = "language_screen_shadow_bottom.svg";
  // static const String languageScreenShadowTop = "language_screen_shadow_top.svg";
  // static const String laptopMobile = "laptop-mobile.svg";
  // static const String listIcon = "list_icon.svg";
  // static const String listPageIcon = "listpageicon.svg";
  // static const String locationPinIcon = "locatiopinicon.svg";
  // static const String mandatoryAssets = "mandatory_assets.svg";
  // static const String mandatoryCourses = "mandatory_courses.svg";
  // static const String mandatoryNumber = "mandatory_number.svg";
  // static const String mandatoryPlay = "mandatory_play.svg";
  // static const String mandatoryPlayComplete = "mandatory_play_complete.svg";
  // static const String mandatoryPlayPauseImage = "mandatory_play_pause_image.svg";
  // static const String mandatorySearch = "mandatory_search.svg";
  // static const String mandatorySearchFill = "mandatory_search_fill.svg";
  // static const String messageSmile = "message-smile.svg";
  // static const String messageQuestion = "message_question_icon.svg";
  // static const String minusIcon = "minus_icon.svg";
  // static const String mobile = "mobile.svg";
  // static const String outlinedList = "outlined_list.svg";
  // static const String penIcon = "pen_icon.svg";
  // static const String phoneIcon = "phone_icon.svg";
  // static const String phoneNumberOtpLogo = "phone_number_otp_logo.svg";
  // static const String plusIcon = "plus_icon.svg";
  // static const String popUpIcon = "pop_up_icon.svg";
  // static const String prePaidCard = "pre_paid_card.svg";
  // static const String privacyIcon = "privacy_icon.svg";
  // static const String profileSelected = "profile_selected.svg";
  // static const String profileUnSelected = "profile_unselected.svg";
  // static const String rightArrow = "right_arrow.svg";
  // static const String rightArrowGreen = "right_arrow_green.svg";
  // static const String settingsIcon = "settings_icon.svg";
  // static const String shadowBottomSvg = "shadow_bottom.svg";
  // static const String shadowTopSvg = "shadow_top.svg";
  // static const String shareImage = "share_image.svg";
  // static const String shieldWithCheckIcon = "shield_with_check_icon.svg";
  // static const String splash = "splash.svg";
  // static const String stopWatchIcon = "stop_watch_icon.svg";
  // static const String successIcon = "success_icon.svg";
  // static const String suiteCaseIcon = "suitecaseicon.svg";
  // static const String supportAgent = "support_agent.svg";
  // static const String swipeUp = "swipe_up.svg";
  // static const String uaePassThumb = "uae_pass_thumb.svg";
  // static const String uaePassLogo = "uaepass_logo.svg";
  // static const String ukFlagIcon = "uk_flag_icon.svg";
  // static const String unlink = "unlink.svg";
  // static const String upArrow = "up_arrow.svg";
  // static const String userCircleIcon = "user_circle_icon.svg";
  // static const String userIcon = "user_icon.svg";
  // static const String videoPauseIcon = "video_pause_icon.svg";
  // static const String videoPlayIcon = "video_play_icon.svg";
  // static const String walletSelected = "wallet_selected.svg";
  // static const String walletUnSelected = "wallet_unselected.svg";
  // static const String warning = "warning.svg";
  // static const String woman = "woman.svg";
  // static const String filterWhiteIcon = "filter_white_icon.svg";
  // static const String sortWhiteIcon = "sort_white_icon.svg";
  // static const String radioCircle = "radio_circle.svg";
  // static const String listSmallGrey = "list_small_grey.svg";
  // static const String listSmallWhite = "list_small_white.svg";
  // static const String starIcon = "star_icon.svg";
  // static const String heartButton = "heart_button.svg";
  // static const String searchIcon = "search_icon.svg";
  // static const String crossIcon = "cross_icon.svg";
  // static const String pieChartIconOne = "pie_chart_icon_one.svg";
  // static const String pieChartIconTwo = "pie_chart_icon_two.svg";
  // static const String emptyWishlistIcon = "empty_wishlist.svg";
  // static const String wineBottleIcon = "wine_bottle.svg";

  //liquor app icons
  // static const String liquorBell = "liquor_bell.svg";
  // static const String liquorFilter = "liquor_filter.svg";
  // static const String liquorMagnifyingGlass = "liquor_magnifying_glass.svg";
  // static const String searchIconAppBar = "search.svg";
  // static const String liquorShoppingCart = "liquor_shopping_cart.svg";
  // static const String liquorRightArrowOutlined = "right_arrow_outlined.svg";
  // static const String appBarLeftArrow = "left_arrow.svg";
  // static const String glass = "glass.svg";
  // static const String glassIcon = "glass_icon.svg";
  // static const String categoryIcon = "categories.svg";
  // static const String heartIcon = "heart_icon.svg";
  // static const String homeIcon = "home.svg";
  // static const String myAccountIcon = "my_account.svg";
  // static const String glassActiveIcon = "glass_active_icon.svg";
  // static const String heartActiveIcon = "heart_active_icon.svg";
  // static const String homeActiveIcon = "home_active_icon.svg";
  // static const String myAccountActiveIcon = "my_acc_active.svg";
  // static const String homeBellIcon = "home_bell.svg";
  // static const String homeCartIcon = "home_cart.svg";
  // static const String googleSvg = "google.svg";
  // static const String fbSvg = "facebook.svg";
  // static const String eyeClosedIcon = "visibility_off.svg";
  // static const String eyeIcon = "eye.svg";
  // static const String orderBadge = "order_badge.svg";
  // static const String lockSvg = "lock.svg";
  // static const String arrowAccount = "arrow_account.svg";
  // static const String logBin = "logbin.svg";
  //
  // static const String aboutInfo = "about_info.svg";
  // static const String editProfile = "edit_profile.svg";
  // static const String lockIcon = "lock_icon.svg";
  // static const String logOutLead = "logout_lead.svg";
  // static const String privacy = "privacy_icon.svg";
  // static const String chatIcon = "chat_icon.svg";
  // static const String forwardArrow = 'CaretLeft.svg';

  //liquor app images
  static const String wine = "${assetImagePathIcons}wine.png";
  static const String wineBottle = "${assetImagePathIcons}wine_bottle.png";
  static const String bowmoreWine = "${assetImagePathIcons}bowmore_wine.png";
  static const String blackWine = "${assetImagePathIcons}black_wine.png";
  static const String tick_image = "${assetImagePathIcons}tick_image.png";
  static const String splash_screen = "${assetImagePathIcons}splash.png";
  static const String login_bg = "${assetImagePathIcons}login_bg.png";
  static const String homeCrousel = "${assetImagePathIcons}home_crousel.png";
  static const String dropDownArrow = "${assetImagePathIcons}drop_down_arrow.png";
  static const String logo = "${assetImagePathIcons}app_icon.png";
  static const String addIcon = "${assetImagePathIcons}add_icon.png";
  static const String menuIcon = "${assetImagePathIcons}menu.png";

  // static const String searchMagnifyingGlass = "${assetImagePathIcons}MagnifyingGlass.png";
  static const String filterIcon = "filter_icon.png";

  static const String google = "${assetImagePathIcons}ggl.png";
  static const String facebook = "${assetImagePathIcons}fb.png";
  static const String crousel = "${assetImagePathIcons}crousel.png";
  static const String curveLog = "${assetImagePathIcons}curve.png";
  static const String lockImage = "lock.png";
  static const String passwordImage = "${assetImagePathIcons}password_image.png";
  static const String profileImg = "${assetImagePathIcons}profileImg.png";
  static const String resetLock = "reset-password.png";
  static const String profileImgUser = "profile.png";
  static const String logOutPng = "logout.png";
  static const String deleteImgPng = "delete_icon.png";
  static const String orderDeleteIconPng = "order_delete_icon.png";
  static const String changePass = "change_pass.png";
  static const String jeweleryMagnifyingGlass = "jewelery_magnifying_glass.svg";
  static const String noSearchResults = "no_search_data_icon.svg";
  static const String shareIcon = "share_icon.svg";
  static const String visibilityOff = "visibility_off.svg";
  static const String searchIconSvg = 'MagnifyingGlass2.svg';
  static const String about_iconPng = "${assetImagePathIcons}about_icon.png";

  //nexgen images

  static const String loginScreenBg = "Login.svg";
  static const String homeScreenBg = 'Home.svg';
  static const String welcomeScreenBg = "WelcomeScreen.svg";

}
