// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrX3C59gkVzYxOsVxiusN9j1z5N_M8B60',
    appId: '1:447004257941:web:9673bc1c65965133e1f59c',
    messagingSenderId: '447004257941',
    projectId: 'grocery-1c982',
    authDomain: 'grocery-1c982.firebaseapp.com',
    storageBucket: 'grocery-1c982.appspot.com',
    measurementId: 'G-BLNNG0QQGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKweGRmlyjO_5Jnb_XUaJyRveEEj76RM',
    appId: '1:447004257941:android:6228f7f4b2aa7f76e1f59c',
    messagingSenderId: '447004257941',
    projectId: 'grocery-1c982',
    storageBucket: 'grocery-1c982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHIDvyn03sbX44286xyaVod85SYjDthg',
    appId: '1:447004257941:ios:d8f95dab9717f182e1f59c',
    messagingSenderId: '447004257941',
    projectId: 'grocery-1c982',
    storageBucket: 'grocery-1c982.appspot.com',
    iosBundleId: 'com.damco.liquor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHIDvyn03sbX44286xyaVod85SYjDthg',
    appId: '1:447004257941:ios:9efba387e0f5a050e1f59c',
    messagingSenderId: '447004257941',
    projectId: 'grocery-1c982',
    storageBucket: 'grocery-1c982.appspot.com',
    iosBundleId: 'com.grocery.app',
  );
}
